# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-08-16 19:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RewardAssigned',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('int_to', models.IntegerField(blank=True, null=True)),
                ('int_status', models.IntegerField(blank=True, null=True)),
                ('dbl_slab1_percentage', models.FloatField(blank=True, null=True)),
                ('dbl_slab1_amount', models.FloatField(blank=True, null=True)),
                ('dbl_slab2_percentage', models.FloatField(blank=True, null=True)),
                ('dbl_slab2_amount', models.FloatField(blank=True, null=True)),
                ('dbl_slab3_percentage', models.FloatField(blank=True, null=True)),
                ('dbl_slab3_amount', models.FloatField(blank=True, null=True)),
                ('dbl_slab4_percentage', models.FloatField(blank=True, null=True)),
                ('dbl_slab5_amount', models.FloatField(blank=True, null=True)),
                ('dbl_slab4_amount', models.FloatField(blank=True, null=True)),
                ('dbl_slab5_percentage', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reward_assigned',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RewardsAvailable',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dbl_mop_amount', models.FloatField(blank=True, null=True)),
                ('dat_reward', models.DateTimeField(blank=True, null=True)),
                ('json_staff', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rewards_available',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RewardsDetails',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('int_quantity_from', models.BigIntegerField(blank=True, null=True)),
                ('int_quantity_to', models.BigIntegerField(blank=True, null=True)),
                ('dbl_value_from', models.FloatField(blank=True, null=True)),
                ('dbl_value_to', models.FloatField(blank=True, null=True)),
                ('dbl_slab1_percentage', models.FloatField(blank=True, null=True)),
                ('dbl_slab1_amount', models.FloatField(blank=True, null=True)),
                ('dbl_slab2_percentage', models.FloatField(blank=True, null=True)),
                ('dbl_slab2_amount', models.FloatField(blank=True, null=True)),
                ('dbl_slab3_percentage', models.FloatField(blank=True, null=True)),
                ('dbl_slab3_amount', models.FloatField(blank=True, null=True)),
                ('int_map_id', models.BigIntegerField(blank=True, null=True)),
                ('int_map_type', models.IntegerField()),
                ('int_mop_sale', models.IntegerField(blank=True, null=True)),
                ('int_to', models.IntegerField(blank=True, null=True)),
                ('int_status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rewards_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RewardsMaster',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dat_from', models.DateTimeField(blank=True, null=True)),
                ('dat_to', models.DateTimeField(blank=True, null=True)),
                ('vchr_area_type', models.CharField(blank=True, max_length=20, null=True)),
                ('json_branch', django.contrib.postgres.fields.jsonb.JSONField()),
                ('vchr_reward_name', models.CharField(blank=True, max_length=250, null=True)),
                ('dbl_slab1_percentage', models.FloatField(blank=True, null=True)),
                ('dbl_slab2_percentage', models.FloatField(blank=True, null=True)),
                ('dbl_slab3_percentage', models.FloatField(blank=True, null=True)),
                ('dat_created_at', models.DateTimeField(auto_now_add=True)),
                ('int_status', models.IntegerField(blank=True, null=True)),
                ('dbl_slab4_percentage', models.FloatField(blank=True, null=True)),
                ('dbl_slab5_percentage', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rewards_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RewardsPaid',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dbl_paid', models.FloatField()),
                ('int_status', models.IntegerField(blank=True, null=True)),
                ('dat_paid', models.DateTimeField(auto_now_add=True)),
                ('dat_acknowledge', models.DateTimeField(blank=True, null=True)),
                ('vchr_transaction_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'rewards_paid',
                'managed': False,
            },
        ),
    ]
