# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-08-16 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hierarchy',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('int_level', models.SmallIntegerField(blank=True, null=True)),
                ('vchr_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'hierarchy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HierarchyData',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_name', models.CharField(blank=True, max_length=100, null=True)),
                ('vchr_code', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'hierarchy_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HierarchyGroups',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_name', models.CharField(blank=True, max_length=50, null=True)),
                ('int_status', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hierarchy_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HierarchyLevel',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('int_mode', models.IntegerField(blank=True, default=0, null=True)),
                ('dat_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('dat_updated', models.DateTimeField(auto_now=True, null=True)),
                ('int_status', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'db_table': 'hierarchy_level',
                'managed': False,
            },
        ),
    ]
