# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-08-16 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_code', models.CharField(blank=True, max_length=15, null=True)),
                ('vchr_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'district',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_name', models.CharField(blank=True, max_length=100, null=True)),
                ('vchr_pin_code', models.CharField(blank=True, max_length=10, null=True)),
                ('vchr_district', models.CharField(blank=True, max_length=50, null=True)),
                ('vchr_state', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocationMaster',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('int_code', models.BigIntegerField(blank=True, null=True)),
                ('vchr_location', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'location_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_name', models.CharField(blank=True, max_length=20, null=True)),
                ('vchr_code', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'states',
                'managed': False,
            },
        ),
    ]
