# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-29 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dat_issue', models.DateTimeField(blank=True, null=True)),
                ('int_fop', models.IntegerField(blank=True, null=True)),
                ('dbl_amount', models.FloatField(blank=True, null=True)),
                ('vchr_remarks', models.TextField(blank=True, null=True)),
                ('int_doc_status', models.IntegerField(blank=True, null=True)),
                ('dat_created', models.DateTimeField(blank=True, null=True)),
                ('dat_updated', models.DateTimeField(blank=True, null=True)),
                ('int_pstatus', models.IntegerField(blank=True, null=True)),
                ('int_receipt_type', models.IntegerField(blank=True, null=True)),
                ('vchr_bank', models.CharField(blank=True, max_length=50, null=True)),
                ('vchr_transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('dat_approval', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'receipt',
            },
        ),
    ]
