# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-08-16 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartialReceipt',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_branchcode', models.CharField(blank=True, max_length=20, null=True)),
                ('vchr_item_code', models.CharField(blank=True, max_length=20, null=True)),
                ('json_data', models.TextField(blank=True, null=True)),
                ('fk_enquiry_master_id', models.BigIntegerField(blank=True, null=True)),
                ('dat_created', models.DateTimeField(blank=True)),
                ('int_status', models.IntegerField(blank=True, null=True)),
                ('bln_service', models.NullBooleanField()),
            ],
            options={
                'db_table': 'partial_receipt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReceiptInvoiceMatching',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dbl_amount', models.FloatField(blank=True, null=True)),
                ('dat_created', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'receipt_invoice_matching',
                'managed': False,
            },
        ),
    ]
