# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-08-16 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_name', models.CharField(blank=True, max_length=100, null=True)),
                ('vchr_email', models.CharField(blank=True, max_length=200, null=True)),
                ('int_mobile', models.BigIntegerField(blank=True, null=True)),
                ('txt_address', models.TextField(blank=True, null=True)),
                ('vchr_gst_no', models.CharField(blank=True, max_length=30, null=True)),
                ('int_otp_number', models.BigIntegerField(blank=True, null=True)),
                ('int_loyalty_points', models.BigIntegerField(blank=True, default=0, null=True)),
                ('int_redeem_point', models.BigIntegerField(blank=True, default=0, null=True)),
                ('dbl_purchase_amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('vchr_loyalty_card_number', models.CharField(blank=True, max_length=50, null=True)),
                ('vchr_code', models.CharField(blank=True, max_length=25, null=True)),
                ('int_edit_count', models.IntegerField(blank=True, null=True)),
                ('vchr_otp', models.CharField(blank=True, max_length=10, null=True)),
                ('dat_exp', models.DateTimeField(blank=True, null=True)),
                ('int_cust_type', models.IntegerField(blank=True, default=0, null=True)),
                ('dbl_credit_balance', models.FloatField(blank=True, default=0, null=True)),
                ('dbl_credit_limit', models.FloatField(blank=True, default=0, null=True)),
                ('cust_smsaccess', models.NullBooleanField()),
                ('cust_salutation', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'customer_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerOccasionsModel',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_occasion_name', models.CharField(max_length=40)),
                ('dat_occasion_date', models.DateField()),
            ],
            options={
                'db_table': 'customer_app_customeroccasionsmodel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerRating',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_feedback', models.TextField(blank=True, null=True)),
                ('dbl_rating', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer_rating',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalesCustomerDetails',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dat_created', models.DateTimeField(blank=True, null=True)),
                ('vchr_name', models.CharField(blank=True, max_length=100, null=True)),
                ('vchr_email', models.CharField(blank=True, max_length=200, null=True)),
                ('int_mobile', models.BigIntegerField(blank=True, null=True)),
                ('int_loyalty_points', models.BigIntegerField(blank=True, null=True)),
                ('int_redeem_point', models.BigIntegerField(blank=True, null=True)),
                ('dbl_purchase_amount', models.FloatField(blank=True, null=True)),
                ('vchr_loyalty_card_number', models.CharField(blank=True, max_length=50, null=True)),
                ('txt_address', models.TextField(blank=True, null=True)),
                ('vchr_gst_no', models.CharField(blank=True, max_length=30, null=True)),
                ('int_otp_number', models.BigIntegerField(blank=True, null=True)),
                ('vchr_code', models.CharField(blank=True, max_length=25, null=True)),
                ('int_cust_type', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'sales_customer_details',
                'managed': False,
            },
        ),
    ]
