# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-08-16 19:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_coupon_code', models.CharField(blank=True, max_length=30, null=True)),
                ('dat_expiry', models.DateField(blank=True, null=True)),
                ('int_discount_percentage', models.IntegerField(blank=True, null=True)),
                ('bint_max_discount_amt', models.BigIntegerField(blank=True, null=True)),
                ('bint_min_purchase_amt', models.BigIntegerField(blank=True, null=True)),
                ('int_max_usage_no', models.IntegerField(blank=True, null=True)),
                ('dat_created', models.DateTimeField(blank=True, null=True)),
                ('dat_updated', models.DateTimeField(blank=True, null=True)),
                ('int_which', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'coupon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StaffCouponDetails',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('json_brand', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('json_item_category', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('json_item_group', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('dbl_discount_percent', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'staff_coupon_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StaffCouponMaster',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('int_employee', models.SmallIntegerField(blank=True, null=True)),
                ('int_not_employee', models.SmallIntegerField(blank=True, null=True)),
                ('dat_created', models.DateTimeField(blank=True, null=True)),
                ('dat_updated', models.DateTimeField(blank=True, null=True)),
                ('int_status', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'staff_coupon_master',
                'managed': False,
            },
        ),
    ]
