# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-08-16 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dat_efct_from', models.DateTimeField(blank=True, null=True)),
                ('dat_created', models.DateTimeField(blank=True, null=True)),
                ('dat_updated', models.DateTimeField(blank=True, null=True)),
                ('int_status', models.IntegerField(blank=True, null=True)),
                ('dbl_supp_amnt', models.FloatField(blank=True, null=True)),
                ('dbl_cost_amnt', models.FloatField(blank=True, null=True)),
                ('dbl_mop', models.FloatField(blank=True, null=True)),
                ('dbl_mrp', models.FloatField(blank=True, null=True)),
                ('dbl_my_amt', models.FloatField(blank=True, null=True)),
                ('dbl_dealer_amt', models.FloatField(blank=True, null=True)),
                ('int_myg_amt', models.FloatField(blank=True, null=True)),
                ('int_dealer_amt', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'price_list',
                'managed': False,
            },
        ),
    ]
