# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-08-16 19:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('int_qty', models.IntegerField(blank=True, null=True)),
                ('dbl_amount', models.FloatField(blank=True, null=True)),
                ('dbl_selling_price', models.FloatField(blank=True, null=True)),
                ('jsn_imei', django.contrib.postgres.fields.jsonb.JSONField()),
                ('dat_returned', models.DateField(blank=True, null=True)),
                ('dat_created', models.DateTimeField(blank=True, null=True)),
                ('dat_updated', models.DateTimeField(blank=True, null=True)),
                ('int_doc_status', models.IntegerField(blank=True, null=True)),
                ('bln_damaged', models.NullBooleanField()),
                ('vchr_image', models.CharField(blank=True, max_length=350, null=True)),
                ('vchr_remark', models.CharField(blank=True, max_length=500, null=True)),
                ('vchr_doc_code', models.CharField(blank=True, max_length=50, null=True)),
                ('dbl_indirect_discount', models.FloatField(blank=True, null=True)),
                ('dbl_discount', models.FloatField(blank=True, null=True)),
                ('dbl_buyback', models.FloatField(blank=True, null=True)),
                ('vchr_old_inv_no', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'sales_return',
                'managed': False,
            },
        ),
    ]
