# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-08-16 19:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContraDetails',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('json_denomination', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contra_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_doc_num', models.CharField(blank=True, max_length=50, null=True)),
                ('dat_payment', models.DateTimeField(blank=True, null=True)),
                ('int_fop', models.IntegerField(blank=True, null=True)),
                ('int_payee_type', models.IntegerField(blank=True, null=True)),
                ('fk_payee_id', models.IntegerField(blank=True, null=True)),
                ('dbl_amount', models.FloatField(blank=True, null=True)),
                ('vchr_remarks', models.TextField(blank=True, null=True)),
                ('int_doc_status', models.IntegerField(blank=True, null=True)),
                ('dat_created', models.DateTimeField(blank=True, null=True)),
                ('dat_updated', models.DateTimeField(blank=True, null=True)),
                ('int_approved', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SapPayment',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_code', models.CharField(blank=True, max_length=50, null=True)),
                ('vchr_description', models.CharField(blank=True, max_length=150, null=True)),
                ('dbl_amount', models.FloatField(blank=True, null=True)),
                ('int_tran_id', models.IntegerField(blank=True, null=True)),
                ('int_type', models.IntegerField(blank=True, null=True)),
                ('doc_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sap_payment',
                'managed': False,
            },
        ),
    ]
