# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-08-16 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupLevel',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('int_level', models.IntegerField(blank=True, null=True)),
                ('vchr_filter', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'group_level',
                'managed': False,
            },
        ),
    ]
