# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-08-16 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayClosureDetails',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dat_time', models.DateTimeField(blank=True, null=True)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('json_dayclosure', models.TextField(blank=True, null=True)),
                ('int_closed', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'day_closure_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DayClosureMaster',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_name', models.CharField(max_length=50)),
                ('bln_active', models.NullBooleanField()),
            ],
            options={
                'db_table': 'day_closure_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DayClosureNotTally',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dat_time', models.DateTimeField(blank=True, null=True)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('json_dayclosure', models.TextField(blank=True, null=True)),
                ('int_status', models.IntegerField()),
                ('vchr_remark', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'day_closure_not_tally',
                'managed': False,
            },
        ),
    ]
