# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-08-16 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryFinance',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_finance_status', models.CharField(blank=True, max_length=20, null=True)),
                ('vchr_remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('dbl_max_amt', models.FloatField(blank=True, null=True)),
                ('vchr_name_in_card', models.CharField(blank=True, max_length=50, null=True)),
                ('vchr_delivery_order_no', models.CharField(blank=True, max_length=50, null=True)),
                ('bln_eligible', models.NullBooleanField()),
                ('int_status', models.IntegerField(blank=True, default=0, null=True)),
                ('int_bajaj', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'enquiry_finance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FinanceCustomerDetails',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_id_type', models.CharField(blank=True, max_length=30, null=True)),
                ('vchr_id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('vchr_pan_number', models.CharField(blank=True, max_length=30, null=True)),
                ('vchr_bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bint_account_number', models.BigIntegerField(blank=True, null=True)),
                ('vchr_branch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('vchr_cheque_number', models.CharField(blank=True, max_length=50, null=True)),
                ('vchr_initial_payment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('dbl_down_payment_amount', models.FloatField(blank=True, null=True)),
                ('dbl_processing_fee', models.FloatField(blank=True, null=True)),
                ('dbl_margin_money', models.FloatField(blank=True, null=True)),
                ('dbl_dbd_amount', models.FloatField(blank=True, null=True)),
                ('dbl_service_charge', models.FloatField(blank=True, null=True)),
                ('dbl_net_loan_amount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'finance_customer_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FinanceSchema',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_schema', models.CharField(blank=True, max_length=50, null=True)),
                ('dat_from', models.DateField(blank=True, null=True)),
                ('dat_to', models.DateField(blank=True, null=True)),
                ('dat_created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'finance_scheme',
                'managed': False,
            },
        ),
    ]
