# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-08-16 19:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_module_name', models.CharField(max_length=50)),
                ('vchr_short_code', models.CharField(max_length=5)),
                ('int_number', models.IntegerField()),
            ],
            options={
                'db_table': 'document',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrnDetails',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('int_qty', models.IntegerField(blank=True, null=True)),
                ('int_free', models.IntegerField(blank=True, null=True)),
                ('int_avail', models.IntegerField(blank=True, null=True)),
                ('int_damaged', models.IntegerField(blank=True, null=True)),
                ('dbl_costprice', models.FloatField(blank=True, null=True)),
                ('dbl_dscnt_percent', models.FloatField(blank=True, null=True)),
                ('dbl_dscnt_perunit', models.FloatField(blank=True, null=True)),
                ('dbl_discount', models.FloatField(blank=True, null=True)),
                ('jsn_tax', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('dbl_tax', models.FloatField(blank=True, null=True)),
                ('dbl_ppu', models.FloatField(blank=True, null=True)),
                ('dbl_total_amount', models.FloatField(blank=True, null=True)),
                ('vchr_batch_no', models.CharField(blank=True, max_length=30, null=True)),
                ('dbl_perpie_aditn', models.FloatField(blank=True, null=True)),
                ('dbl_perpie_dedctn', models.FloatField(blank=True, null=True)),
                ('jsn_imei', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('jsn_imei_avail', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('jsn_imei_dmgd', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'grn_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrnMaster',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_purchase_num', models.CharField(blank=True, max_length=20, null=True)),
                ('dat_purchase', models.DateTimeField(blank=True, null=True)),
                ('int_fop', models.IntegerField(blank=True, null=True)),
                ('dat_pay_before', models.DateTimeField(blank=True, null=True)),
                ('dbl_total', models.FloatField(blank=True, null=True)),
                ('vchr_notes', models.TextField(blank=True, null=True)),
                ('dat_created', models.DateTimeField(blank=True, null=True)),
                ('dat_updated', models.DateTimeField(blank=True, null=True)),
                ('int_doc_status', models.IntegerField(blank=True, null=True)),
                ('dbl_addition', models.FloatField(blank=True, null=True)),
                ('dbl_deduction', models.FloatField(blank=True, null=True)),
                ('dbl_roundoff_value', models.FloatField(blank=True, null=True)),
                ('int_approve', models.IntegerField(blank=True, null=True)),
                ('vchr_bill_no', models.CharField(blank=True, max_length=20, null=True)),
                ('dat_bill', models.DateTimeField(blank=True, null=True)),
                ('vchr_reject_reason', models.TextField(blank=True, null=True)),
                ('dbl_bill_amount', models.FloatField(blank=True, null=True)),
                ('vchr_bill_image', models.CharField(blank=True, max_length=350, null=True)),
            ],
            options={
                'db_table': 'grn_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrnrDetails',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('int_qty', models.IntegerField(blank=True, null=True)),
                ('dbl_tax_rate', models.FloatField(blank=True, null=True)),
                ('jsn_imei', models.TextField(blank=True, null=True)),
                ('vchr_batch_no', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'grnr_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrnrImeiDetails',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('jsn_imei', models.TextField(blank=True, null=True)),
                ('jsn_batch_no', models.TextField(blank=True, null=True)),
                ('int_qty', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'grnr_imei_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrnrMaster',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_purchase_return_num', models.CharField(blank=True, max_length=80, null=True)),
                ('dat_purchase_return', models.DateTimeField(blank=True, null=True)),
                ('dat_created', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'grnr_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PoDetails',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('int_qty', models.IntegerField(blank=True, null=True)),
                ('dbl_prate', models.FloatField(blank=True, null=True)),
                ('dbl_total_amount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'po_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PoMaster',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_po_num', models.CharField(blank=True, max_length=20, null=True)),
                ('dat_po', models.DateTimeField(blank=True, null=True)),
                ('dat_po_expiry', models.DateTimeField(blank=True, null=True)),
                ('vchr_notes', models.TextField(blank=True, null=True)),
                ('dat_created', models.DateTimeField(blank=True, null=True)),
                ('dat_updated', models.DateTimeField(blank=True, null=True)),
                ('int_doc_status', models.IntegerField(blank=True, null=True)),
                ('int_status', models.IntegerField(blank=True, null=True)),
                ('int_total_qty', models.IntegerField(blank=True, null=True)),
                ('dbl_total_amount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'po_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseVoucher',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_voucher_num', models.CharField(blank=True, max_length=20, null=True)),
                ('dbl_voucher_amount', models.FloatField(blank=True, null=True)),
                ('vchr_voucher_bill_no', models.CharField(blank=True, max_length=20, null=True)),
                ('dat_voucher_bill', models.DateTimeField(blank=True, null=True)),
                ('dat_created', models.DateTimeField(blank=True, null=True)),
                ('dat_updated', models.DateTimeField(blank=True, null=True)),
                ('vchr_remark', models.TextField(blank=True, null=True)),
                ('int_doc_status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'purchase_voucher',
                'managed': False,
            },
        ),
    ]
