# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-08-16 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_jv_num', models.CharField(blank=True, max_length=100, null=True)),
                ('dat_journal', models.DateField(blank=True, null=True)),
                ('int_debit_type', models.IntegerField(blank=True, null=True)),
                ('fk_debit_id', models.IntegerField(blank=True, null=True)),
                ('int_credit_type', models.IntegerField(blank=True, null=True)),
                ('fk_credit_id', models.IntegerField(blank=True, null=True)),
                ('dbl_amount', models.FloatField(blank=True, null=True)),
                ('vchr_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('dat_created', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'journal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dat_created', models.DateTimeField(blank=True, null=True)),
                ('int_accounts_id', models.IntegerField(blank=True, null=True)),
                ('int_account_type', models.IntegerField(blank=True, null=True)),
                ('dbl_debit', models.FloatField()),
                ('dbl_credit', models.FloatField()),
                ('int_document_id', models.IntegerField(blank=True, null=True)),
                ('int_document_type', models.IntegerField(blank=True, null=True)),
                ('vchr_status', models.CharField(blank=True, max_length=20, null=True)),
                ('dat_updated', models.DateTimeField(blank=True, null=True)),
                ('int_type', models.IntegerField(blank=True, null=True)),
                ('int_lock', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transaction',
                'managed': False,
            },
        ),
    ]
