# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-08-16 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpCategory',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_code', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('vchr_name', models.CharField(blank=True, max_length=30, null=True)),
                ('int_status', models.IntegerField(blank=True, null=True)),
                ('dat_created', models.DateTimeField(blank=True, null=True)),
                ('dat_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'emp_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OtherCategory',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_name', models.CharField(blank=True, max_length=50, null=True)),
                ('int_status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'other_category',
                'managed': False,
            },
        ),
    ]
