# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-29 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyCard',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_card_name', models.CharField(blank=True, max_length=50, null=True)),
                ('int_price_range_from', models.BigIntegerField(blank=True, null=True)),
                ('int_price_range_to', models.BigIntegerField(blank=True, null=True)),
                ('dbl_loyalty_percentage', models.FloatField(blank=True, null=True)),
                ('dbl_min_purchase_amount', models.FloatField(blank=True, null=True)),
                ('int_min_redeem_days', models.IntegerField(blank=True, null=True)),
                ('int_min_redeem_point', models.BigIntegerField(blank=True, null=True)),
                ('bln_status', models.NullBooleanField()),
                ('dat_created', models.DateTimeField(blank=True, null=True)),
                ('dat_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'loyalty_card',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyCardStatus',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_status', models.CharField(blank=True, max_length=50, null=True)),
                ('dat_eligible', models.DateField(blank=True, null=True)),
                ('dat_given', models.DateField(blank=True, null=True)),
                ('vchr_remark', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'loyalty_card_status',
            },
        ),
    ]
