# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-08-16 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddAttachments',
            fields=[
                ('pk_bint_id', models.AutoField(primary_key=True, serialize=False)),
                ('vchr_logo', models.FileField(blank=True, max_length=300, null=True, upload_to='files/')),
            ],
            options={
                'db_table': 'add_attachments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('pk_bint_id', models.AutoField(primary_key=True, serialize=False)),
                ('vchr_module_name', models.CharField(max_length=50)),
                ('vchr_short_code', models.CharField(max_length=5)),
                ('int_number', models.IntegerField()),
            ],
            options={
                'db_table': 'document',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnquiryMaster',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_enquiry_num', models.CharField(max_length=50)),
                ('vchr_customer_type', models.CharField(max_length=50)),
                ('bln_sms', models.NullBooleanField()),
                ('chr_doc_status', models.CharField(max_length=1)),
                ('dat_created_at', models.DateTimeField(blank=True, null=True)),
                ('dat_updated_at', models.DateTimeField(blank=True, null=True)),
                ('vchr_hash', models.TextField(blank=True, null=True)),
                ('dbl_partial_amt', models.FloatField(blank=True, null=True)),
                ('vchr_remarks', models.TextField(blank=True, null=True)),
                ('int_customer_type', models.IntegerField(blank=True, null=True)),
                ('vchr_order_num', models.CharField(blank=True, max_length=30, null=True)),
                ('int_sale_type', models.IntegerField(blank=True, null=True)),
                ('vchr_reference_num', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'enquiry_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Forex',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dbl_amount', models.FloatField(blank=True, null=True)),
                ('vchr_remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('vchr_from', models.CharField(max_length=50)),
                ('vchr_to', models.CharField(max_length=50)),
                ('vchr_enquiry_status', models.CharField(max_length=50)),
                ('dbl_estimated_amount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'forex',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dat_check_in', models.DateField()),
                ('dat_check_out', models.DateField()),
                ('vchr_city', models.CharField(max_length=50)),
                ('vchr_nationality', models.CharField(max_length=50)),
                ('int_rooms', models.IntegerField(blank=True, null=True)),
                ('dbl_budget', models.FloatField(blank=True, null=True)),
                ('vchr_meal_type', models.CharField(blank=True, max_length=50, null=True)),
                ('vchr_remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('vchr_star_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('vchr_enquiry_status', models.CharField(max_length=50)),
                ('dbl_estimated_amount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hotel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_code', models.CharField(blank=True, max_length=100, null=True)),
                ('vchr_details', models.CharField(blank=True, max_length=100, null=True)),
                ('bln_item', models.NullBooleanField()),
                ('bln_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'offers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_description', models.CharField(blank=True, max_length=250, null=True)),
                ('vchr_enquiry_status', models.CharField(max_length=50)),
                ('dbl_estimated_amount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'other',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dat_from', models.DateField()),
                ('dat_to', models.DateField()),
                ('int_adults', models.IntegerField(blank=True, null=True)),
                ('int_children', models.IntegerField(blank=True, null=True)),
                ('int_infants', models.IntegerField(blank=True, null=True)),
                ('dbl_budget', models.FloatField(blank=True, null=True)),
                ('vchr_sightseeing', models.CharField(blank=True, max_length=50, null=True)),
                ('vchr_destination', models.CharField(blank=True, max_length=50, null=True)),
                ('vchr_remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('vchr_enquiry_status', models.CharField(max_length=50)),
                ('dbl_estimated_amount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'package',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_room_type', models.CharField(blank=True, max_length=50, null=True)),
                ('int_adults', models.IntegerField(blank=True, null=True)),
                ('int_children', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rooms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dat_from', models.DateTimeField()),
                ('dat_to', models.DateTimeField()),
                ('vchr_pick_up', models.CharField(blank=True, max_length=50, null=True)),
                ('vchr_drop_off', models.CharField(blank=True, max_length=50, null=True)),
                ('vchr_vehical_type', models.CharField(blank=True, max_length=50, null=True)),
                ('int_seats', models.IntegerField(blank=True, null=True)),
                ('int_adults', models.IntegerField(blank=True, null=True)),
                ('int_children', models.IntegerField(blank=True, null=True)),
                ('int_infants', models.IntegerField(blank=True, null=True)),
                ('vchr_vehical_preferred', models.CharField(blank=True, max_length=50, null=True)),
                ('vchr_facility', models.CharField(blank=True, max_length=50, null=True)),
                ('vchr_remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('vchr_enquiry_status', models.CharField(max_length=50)),
                ('dbl_estimated_amount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transport',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TravelInsurance',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_insurance_type', models.CharField(max_length=50)),
                ('dat_from', models.DateField()),
                ('dat_to', models.DateField()),
                ('int_adults', models.IntegerField(blank=True, null=True)),
                ('int_children', models.IntegerField(blank=True, null=True)),
                ('int_infants', models.IntegerField(blank=True, null=True)),
                ('vchr_remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('vchr_enquiry_status', models.CharField(max_length=50)),
                ('dbl_estimated_amount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'travel_insurance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_visa_category', models.CharField(max_length=50)),
                ('vchr_visit_type', models.CharField(max_length=50)),
                ('vchr_duration_type', models.CharField(max_length=50)),
                ('dbl_duration', models.FloatField(blank=True, null=True)),
                ('int_adults', models.IntegerField(blank=True, null=True)),
                ('int_children', models.IntegerField(blank=True, null=True)),
                ('int_infants', models.IntegerField(blank=True, null=True)),
                ('vchr_remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('vchr_enquiry_status', models.CharField(max_length=50)),
                ('dbl_estimated_amount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'visa',
                'managed': False,
            },
        ),
    ]
