# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-08-16 19:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('jsn_terms', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('int_status', models.IntegerField(blank=True, null=True)),
                ('dat_created', models.DateTimeField(blank=True, null=True)),
                ('dat_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'terms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'type',
                'managed': False,
            },
        ),
    ]
