# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-08-16 19:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchStockDetails',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('int_qty', models.IntegerField(blank=True, null=True)),
                ('jsn_imei', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('jsn_imei_avail', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('jsn_imei_dmgd', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('jsn_batch_no', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('int_received', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'branch_stock_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BranchStockImeiDetails',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('jsn_imei', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('jsn_batch_no', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('jsn_imei_reached', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('jsn_batch_reached', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('int_qty', models.IntegerField(blank=True, null=True)),
                ('int_received', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'branch_stock_imei_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BranchStockMaster',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dat_stock', models.DateTimeField(blank=True, null=True)),
                ('dbl_tax', models.FloatField(blank=True, null=True)),
                ('dbl_amount', models.FloatField(blank=True, null=True)),
                ('jsn_tax', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('vchr_sap_doc_num', models.CharField(blank=True, max_length=10, null=True)),
                ('dat_sap_doc_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'branch_stock_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MailingProduct',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_name', models.CharField(blank=True, max_length=100, null=True)),
                ('vchr_email', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'mailing_product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NonSaleable',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dat_created', models.DateTimeField(blank=True, null=True)),
                ('dat_updated', models.DateTimeField(blank=True, null=True)),
                ('int_status', models.IntegerField(blank=True, null=True)),
                ('jsn_non_saleable', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('jsn_status_change', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('vchr_remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'non_saleable',
                'managed': False,
            },
        ),
    ]
