# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-08-16 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_type', models.CharField(blank=True, max_length=20, null=True)),
                ('int_year', models.IntegerField(blank=True, null=True)),
                ('dat_start', models.DateTimeField(blank=True, null=True)),
                ('dat_end', models.DateTimeField(blank=True, null=True)),
                ('bln_status', models.NullBooleanField()),
            ],
            options={
                'db_table': 'financial_year',
                'managed': False,
            },
        ),
    ]
