# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-08-16 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressSupplier',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_address', models.CharField(blank=True, max_length=185, null=True)),
                ('vchr_email', models.CharField(blank=True, max_length=30, null=True)),
                ('bint_phone_no', models.BigIntegerField(blank=True, null=True)),
                ('int_pin_code', models.IntegerField(blank=True, null=True)),
                ('bln_status', models.NullBooleanField()),
                ('bln_primary', models.NullBooleanField()),
            ],
            options={
                'db_table': 'address_supplier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContactPersonSupplier',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_name', models.CharField(blank=True, max_length=100, null=True)),
                ('vchr_designation', models.CharField(blank=True, max_length=30, null=True)),
                ('vchr_department', models.CharField(blank=True, max_length=30, null=True)),
                ('vchr_office', models.CharField(blank=True, max_length=30, null=True)),
                ('bint_mobile_no', models.BigIntegerField(blank=True, null=True)),
                ('bint_mobile_no2', models.BigIntegerField(blank=True, null=True)),
                ('bln_status', models.NullBooleanField()),
            ],
            options={
                'db_table': 'contact_person_supplier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dat_from', models.DateTimeField(blank=True, null=True)),
                ('vchr_code', models.CharField(blank=True, max_length=50, null=True)),
                ('int_credit_days', models.IntegerField(blank=True, null=True)),
                ('bint_credit_limit', models.BigIntegerField(blank=True, null=True)),
                ('int_po_expiry_days', models.IntegerField(blank=True, null=True)),
                ('vchr_tin_no', models.CharField(blank=True, max_length=50, null=True)),
                ('vchr_cst_no', models.CharField(blank=True, max_length=50, null=True)),
                ('vchr_gstin', models.CharField(blank=True, max_length=100, null=True)),
                ('vchr_gstin_status', models.CharField(blank=True, max_length=50, null=True)),
                ('vchr_account_group', models.CharField(blank=True, max_length=50, null=True)),
                ('vchr_bank_account', models.CharField(blank=True, max_length=50, null=True)),
                ('vchr_pan_no', models.CharField(blank=True, max_length=50, null=True)),
                ('vchr_pan_status', models.CharField(blank=True, max_length=50, null=True)),
                ('is_act_del', models.IntegerField(blank=True, null=True)),
                ('dat_created', models.DateTimeField(blank=True, null=True)),
                ('dat_updated', models.DateTimeField(blank=True, null=True)),
                ('int_batch_no_offset', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'supplier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierLog',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_remarks', models.TextField(blank=True, null=True)),
                ('vchr_status', models.CharField(blank=True, max_length=20, null=True)),
                ('dat_created', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'supplier_log',
                'managed': False,
            },
        ),
    ]
