# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-08-16 19:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourierMaster',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_name', models.CharField(blank=True, max_length=100, null=True)),
                ('vchr_gst_no', models.CharField(blank=True, max_length=100, null=True)),
                ('json_vehicle_no', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'courier_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IsrDetails',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('int_qty', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'isr_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IstDetails',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('int_qty', models.IntegerField(blank=True, null=True)),
                ('jsn_imei', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('dbl_rate', models.FloatField(blank=True, null=True)),
                ('jsn_batch_no', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ist_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dat_request', models.DateTimeField(blank=True, null=True)),
                ('int_status', models.IntegerField(blank=True, null=True)),
                ('dat_created', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'purchase_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequestDetails',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('int_qty', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'purchase_request_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockRequest',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dat_request', models.DateTimeField(blank=True, null=True)),
                ('vchr_stkrqst_num', models.CharField(blank=True, max_length=20, null=True)),
                ('dat_expected', models.DateTimeField(blank=True, null=True)),
                ('vchr_remarks', models.TextField(blank=True, null=True)),
                ('dat_created', models.DateTimeField(blank=True, null=True)),
                ('dat_updated', models.DateTimeField(blank=True, null=True)),
                ('int_doc_status', models.IntegerField(blank=True, null=True)),
                ('int_status', models.IntegerField(blank=True, null=True)),
                ('vchr_reject', models.TextField(blank=True, null=True)),
                ('vchr_approve', models.TextField(blank=True, null=True)),
                ('int_automate', models.IntegerField(blank=True, null=True)),
                ('vchr_rej_remark', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_stktransfer_num', models.CharField(blank=True, max_length=20, null=True)),
                ('dat_transfer', models.DateTimeField(blank=True, null=True)),
                ('dat_acknowledge', models.DateTimeField(blank=True, null=True)),
                ('vchr_remarks', models.TextField(blank=True, null=True)),
                ('dat_created', models.DateTimeField(blank=True, null=True)),
                ('dat_updated', models.DateTimeField(blank=True, null=True)),
                ('int_doc_status', models.IntegerField(blank=True, null=True)),
                ('int_acknowledge', models.IntegerField(blank=True, null=True)),
                ('int_status', models.IntegerField(blank=True, null=True)),
                ('vchr_sap_doc_num', models.CharField(blank=True, max_length=10, null=True)),
                ('dat_sap_doc_date', models.DateTimeField(blank=True, null=True)),
                ('vchr_eway_bill_no', models.CharField(blank=True, max_length=25, null=True)),
                ('bln_direct_transfer', models.BooleanField(default=False)),
                ('vchr_vehicle_num', models.CharField(blank=True, max_length=20, null=True)),
                ('vchr_irn_no', models.CharField(blank=True, max_length=100, null=True)),
                ('txt_qr_code', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock_transfer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockTransferImeiDetails',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('jsn_imei', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('jsn_batch_no', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('int_qty', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock_transfer_imei_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransferHistory',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dat_created', models.DateTimeField(blank=True, null=True)),
                ('dat_updated', models.DateTimeField(blank=True, null=True)),
                ('vchr_status', models.CharField(blank=True, max_length=30, null=True)),
                ('int_doc_status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transfer_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransferModeDetails',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('int_medium', models.IntegerField(blank=True, null=True)),
                ('vchr_name_responsible', models.CharField(blank=True, max_length=30, null=True)),
                ('bnt_contact_number', models.BigIntegerField(blank=True, null=True)),
                ('bnt_number', models.CharField(blank=True, max_length=50, null=True)),
                ('dat_created', models.DateTimeField(blank=True, null=True)),
                ('dat_updated', models.DateTimeField(blank=True, null=True)),
                ('int_doc_status', models.IntegerField(blank=True, null=True)),
                ('int_packet_no', models.IntegerField(blank=True, null=True)),
                ('int_packet_received', models.IntegerField(blank=True, null=True)),
                ('dbl_expense', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transfer_mode_details',
                'managed': False,
            },
        ),
    ]
