# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-08-16 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddComboDiscount',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('int_discount_type', models.IntegerField(blank=True, null=True)),
                ('dbl_amt', models.FloatField(blank=True, null=True)),
                ('dbl_percent', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'add_combo_discount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AddComboDiscountItem',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('int_quantity', models.IntegerField(blank=True, null=True)),
                ('dbl_amt', models.FloatField(blank=True, null=True)),
                ('dbl_percent', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'add_combo_discount_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AddComboMaster',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('int_offer_type', models.IntegerField(blank=True, null=True)),
                ('vchr_offer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dbl_amt', models.FloatField(blank=True, null=True)),
                ('int_status', models.IntegerField(blank=True, default=0, null=True)),
                ('int_quantity', models.IntegerField(blank=True, null=True)),
                ('dat_to', models.DateField(blank=True, null=True)),
                ('dat_from', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'add_combo_master',
                'managed': False,
            },
        ),
    ]
