# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-08-16 19:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_name', models.CharField(max_length=50)),
                ('int_status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bank',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Depreciation',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('int_days_upto', models.IntegerField(blank=True, null=True)),
                ('int_dep_percentage', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'depreciation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FinanceDetails',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dbl_finance_amt', models.FloatField(blank=True, null=True)),
                ('dbl_receved_amt', models.FloatField(blank=True, null=True)),
                ('dbl_processing_fee', models.FloatField(blank=True, null=True)),
                ('dbl_margin_fee', models.FloatField(blank=True, null=True)),
                ('dbl_service_amt', models.FloatField(blank=True, null=True)),
                ('dbl_dbd_amt', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'finance_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FinanceScheme',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_schema', models.CharField(blank=True, max_length=30, null=True)),
                ('dat_from', models.DateField(blank=True, null=True)),
                ('dat_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'finance_scheme',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GDPRange',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dbl_from', models.FloatField(blank=True, null=True)),
                ('dbl_to', models.FloatField(blank=True, null=True)),
                ('dbl_amt', models.FloatField(blank=True, null=True)),
                ('int_type', models.IntegerField()),
            ],
            options={
                'db_table': 'gdp_range',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalesMasterJio',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dat_invoice', models.DateField(blank=True, null=True)),
                ('vchr_invoice_num', models.CharField(blank=True, max_length=50, null=True)),
                ('vchr_remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('int_qty', models.IntegerField(blank=True, null=True)),
                ('vchr_batch', models.CharField(blank=True, max_length=50, null=True)),
                ('json_imei', django.contrib.postgres.fields.jsonb.JSONField()),
                ('dbl_total_amt', models.FloatField(blank=True, null=True)),
                ('dbl_rounding_off', models.FloatField(blank=True, null=True)),
                ('int_doc_status', models.IntegerField(blank=True, null=True)),
                ('dat_created', models.DateTimeField(blank=True, null=True)),
                ('dat_updated', models.DateTimeField(blank=True, null=True)),
                ('int_fop', models.IntegerField()),
                ('vchr_card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('vchr_name', models.CharField(blank=True, max_length=100, null=True)),
                ('vchr_reff_number', models.CharField(blank=True, max_length=100, null=True)),
                ('dbl_receved_amt', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sales_master_jio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TheftDetails',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dat_purchase', models.DateField(blank=True, null=True)),
                ('int_days_missing', models.IntegerField(blank=True, null=True)),
                ('int_depreciation_amt', models.BigIntegerField(blank=True, null=True)),
                ('dat_created', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'theft_details',
                'managed': False,
            },
        ),
    ]
