# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-08-16 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaytmPointData',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('int_status', models.SmallIntegerField(blank=True, null=True)),
                ('dat_created', models.DateTimeField(blank=True, null=True)),
                ('dat_updated', models.DateTimeField(blank=True, null=True)),
                ('vchr_ref_num', models.CharField(blank=True, max_length=100, null=True)),
                ('dbl_amount', models.FloatField(blank=True, null=True)),
                ('dbl_pts', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'paytm_point_data',
                'managed': False,
            },
        ),
    ]
