# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-08-16 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryItems',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'category_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupPermissions',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bln_view', models.BooleanField()),
                ('bln_add', models.BooleanField()),
                ('bln_delete', models.BooleanField()),
                ('bln_edit', models.BooleanField()),
                ('bln_download', models.BooleanField()),
            ],
            options={
                'db_table': 'group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_main_category_name', models.CharField(max_length=50)),
                ('vchr_main_category_value', models.CharField(blank=True, max_length=50, null=True)),
                ('int_main_category_order', models.IntegerField(blank=True, null=True)),
                ('vchr_icon_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'main_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_menu_category_name', models.CharField(max_length=50)),
                ('vchr_menu_category_value', models.CharField(blank=True, max_length=50, null=True)),
                ('int_menu_category_order', models.IntegerField(blank=True, null=True)),
                ('bln_has_children', models.NullBooleanField()),
                ('vchr_addurl', models.CharField(blank=True, max_length=50, null=True)),
                ('vchr_viewurl', models.CharField(blank=True, max_length=50, null=True)),
                ('vchr_editurl', models.CharField(blank=True, max_length=50, null=True)),
                ('vchr_listurl', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'menu_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_sub_category_name', models.CharField(max_length=50)),
                ('vchr_sub_category_value', models.CharField(blank=True, max_length=50, null=True)),
                ('int_sub_category_order', models.IntegerField(blank=True, null=True)),
                ('vchr_icon_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'sub_category',
                'managed': False,
            },
        ),
    ]
