# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-08 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_name', models.CharField(max_length=50)),
                ('vchr_hsn_code', models.CharField(blank=True, max_length=50, null=True)),
                ('vchr_sac_code', models.CharField(blank=True, max_length=50, null=True)),
                ('bln_sales', models.NullBooleanField()),
            ],
            options={
                'managed': False,
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Specifications',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_name', models.CharField(max_length=50)),
                ('bln_status', models.NullBooleanField()),
            ],
            options={
                'managed': False,
                'db_table': 'specifications',
            },
        ),
    ]
